# Generated by Django 5.2.4 on 2025-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=50, null=True)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("services", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
