# Generated by Django 5.2.1 on 2025-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="services",
            field=models.CharField(blank=True, null=True),
        ),
    ]
